# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(301, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 281, 131))
        self.groupBox.setMinimumSize(QtCore.QSize(280, 110))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 261, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CH1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH1.setObjectName("CH1")
        self.gridLayout_2.addWidget(self.CH1, 0, 0, 1, 1)
        self.CH2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH2.setObjectName("CH2")
        self.gridLayout_2.addWidget(self.CH2, 0, 1, 1, 1)
        self.CH3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH3.setObjectName("CH3")
        self.gridLayout_2.addWidget(self.CH3, 0, 2, 1, 1)
        self.CH4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH4.setObjectName("CH4")
        self.gridLayout_2.addWidget(self.CH4, 0, 3, 1, 1)
        self.CH5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH5.setObjectName("CH5")
        self.gridLayout_2.addWidget(self.CH5, 0, 4, 1, 1)
        self.CH6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH6.setObjectName("CH6")
        self.gridLayout_2.addWidget(self.CH6, 1, 0, 1, 1)
        self.CH7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH7.setObjectName("CH7")
        self.gridLayout_2.addWidget(self.CH7, 1, 1, 1, 1)
        self.CH8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH8.setObjectName("CH8")
        self.gridLayout_2.addWidget(self.CH8, 1, 2, 1, 1)
        self.CH9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH9.setObjectName("CH9")
        self.gridLayout_2.addWidget(self.CH9, 1, 3, 1, 1)
        self.CH10 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH10.setObjectName("CH10")
        self.gridLayout_2.addWidget(self.CH10, 1, 4, 1, 1)
        self.CH11 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH11.setObjectName("CH11")
        self.gridLayout_2.addWidget(self.CH11, 2, 0, 1, 1)
        self.CH12 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH12.setObjectName("CH12")
        self.gridLayout_2.addWidget(self.CH12, 2, 1, 1, 1)
        self.CH13 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH13.setObjectName("CH13")
        self.gridLayout_2.addWidget(self.CH13, 2, 2, 1, 1)
        self.CH14 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH14.setObjectName("CH14")
        self.gridLayout_2.addWidget(self.CH14, 2, 3, 1, 1)
        self.CH15 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH15.setObjectName("CH15")
        self.gridLayout_2.addWidget(self.CH15, 2, 4, 1, 1)
        self.CH16 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH16.setObjectName("CH16")
        self.gridLayout_2.addWidget(self.CH16, 3, 0, 1, 1)
        self.CH17 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH17.setObjectName("CH17")
        self.gridLayout_2.addWidget(self.CH17, 3, 1, 1, 1)
        self.CH18 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH18.setObjectName("CH18")
        self.gridLayout_2.addWidget(self.CH18, 3, 2, 1, 1)
        self.CH19 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH19.setObjectName("CH19")
        self.gridLayout_2.addWidget(self.CH19, 3, 3, 1, 1)
        self.CH20 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH20.setObjectName("CH20")
        self.gridLayout_2.addWidget(self.CH20, 3, 4, 1, 1)
        self.CH21 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH21.setObjectName("CH21")
        self.gridLayout_2.addWidget(self.CH21, 4, 0, 1, 1)
        self.CH22 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH22.setObjectName("CH22")
        self.gridLayout_2.addWidget(self.CH22, 4, 1, 1, 1)
        self.CH23 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH23.setObjectName("CH23")
        self.gridLayout_2.addWidget(self.CH23, 4, 2, 1, 1)
        self.CH24 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CH24.setObjectName("CH24")
        self.gridLayout_2.addWidget(self.CH24, 4, 3, 1, 1)
        self.selectAllChan = QtWidgets.QCheckBox(self.layoutWidget)
        self.selectAllChan.setObjectName("selectAllChan")
        self.gridLayout_2.addWidget(self.selectAllChan, 4, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 271, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.selectAllWave = QtWidgets.QCheckBox(self.groupBox_2)
        self.selectAllWave.setGeometry(QtCore.QRect(0, 40, 71, 16))
        self.selectAllWave.setObjectName("selectAllWave")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 256, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wave1310 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.wave1310.setObjectName("wave1310")
        self.horizontalLayout.addWidget(self.wave1310)
        self.wave1490 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.wave1490.setObjectName("wave1490")
        self.horizontalLayout.addWidget(self.wave1490)
        self.wave1550 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.wave1550.setObjectName("wave1550")
        self.horizontalLayout.addWidget(self.wave1550)
        self.wave1625 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.wave1625.setObjectName("wave1625")
        self.horizontalLayout.addWidget(self.wave1625)
        self.layoutWidget.raise_()
        self.selectAllWave.raise_()
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 258, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ipaddr = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ipaddr.setObjectName("ipaddr")
        self.gridLayout.addWidget(self.ipaddr, 0, 1, 1, 1)
        self.connect = QtWidgets.QPushButton(self.layoutWidget2)
        self.connect.setObjectName("connect")
        self.gridLayout.addWidget(self.connect, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(self.layoutWidget2)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(180, 270, 81, 76))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.startGridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.startGridLayout.setContentsMargins(0, 0, 0, 0)
        self.startGridLayout.setObjectName("startGridLayout")
        self.save4Replace = QtWidgets.QPushButton(self.layoutWidget3)
        self.save4Replace.setObjectName("save4Replace")
        self.startGridLayout.addWidget(self.save4Replace, 1, 0, 1, 1)
        self.returnLossCheck = QtWidgets.QCheckBox(self.layoutWidget3)
        self.returnLossCheck.setObjectName("returnLossCheck")
        self.startGridLayout.addWidget(self.returnLossCheck, 0, 0, 1, 1)
        self.saveCurrent = QtWidgets.QPushButton(self.layoutWidget3)
        self.saveCurrent.setObjectName("saveCurrent")
        self.startGridLayout.addWidget(self.saveCurrent, 2, 0, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 270, 141, 74))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.switchStep = QtWidgets.QLineEdit(self.layoutWidget4)
        self.switchStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.switchStep.setObjectName("switchStep")
        self.gridLayout_3.addWidget(self.switchStep, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.testStep = QtWidgets.QLineEdit(self.layoutWidget4)
        self.testStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testStep.setObjectName("testStep")
        self.gridLayout_3.addWidget(self.testStep, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.testTime = QtWidgets.QLineEdit(self.layoutWidget4)
        self.testTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testTime.setObjectName("testTime")
        self.gridLayout_3.addWidget(self.testTime, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 301, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "通道选择"))
        self.CH1.setText(_translate("MainWindow", "CH1"))
        self.CH2.setText(_translate("MainWindow", "CH2"))
        self.CH3.setText(_translate("MainWindow", "CH3"))
        self.CH4.setText(_translate("MainWindow", "CH4"))
        self.CH5.setText(_translate("MainWindow", "CH5"))
        self.CH6.setText(_translate("MainWindow", "CH6"))
        self.CH7.setText(_translate("MainWindow", "CH7"))
        self.CH8.setText(_translate("MainWindow", "CH8"))
        self.CH9.setText(_translate("MainWindow", "CH9"))
        self.CH10.setText(_translate("MainWindow", "CH10"))
        self.CH11.setText(_translate("MainWindow", "CH11"))
        self.CH12.setText(_translate("MainWindow", "CH12"))
        self.CH13.setText(_translate("MainWindow", "CH13"))
        self.CH14.setText(_translate("MainWindow", "CH14"))
        self.CH15.setText(_translate("MainWindow", "CH15"))
        self.CH16.setText(_translate("MainWindow", "CH16"))
        self.CH17.setText(_translate("MainWindow", "CH17"))
        self.CH18.setText(_translate("MainWindow", "CH18"))
        self.CH19.setText(_translate("MainWindow", "CH19"))
        self.CH20.setText(_translate("MainWindow", "CH20"))
        self.CH21.setText(_translate("MainWindow", "CH21"))
        self.CH22.setText(_translate("MainWindow", "CH22"))
        self.CH23.setText(_translate("MainWindow", "CH23"))
        self.CH24.setText(_translate("MainWindow", "CH24"))
        self.selectAllChan.setText(_translate("MainWindow", "全选"))
        self.groupBox_2.setTitle(_translate("MainWindow", "波长选择"))
        self.selectAllWave.setText(_translate("MainWindow", "全选"))
        self.wave1310.setText(_translate("MainWindow", "1310nm"))
        self.wave1490.setText(_translate("MainWindow", "1490nm"))
        self.wave1550.setText(_translate("MainWindow", "1550nm"))
        self.wave1625.setText(_translate("MainWindow", "1625nm"))
        self.label.setText(_translate("MainWindow", "IP："))
        self.ipaddr.setText(_translate("MainWindow", "localhost"))
        self.connect.setText(_translate("MainWindow", "连接"))
        self.label_2.setText(_translate("MainWindow", "Port："))
        self.port.setText(_translate("MainWindow", "8100"))
        self.save4Replace.setText(_translate("MainWindow", "开始测试R"))
        self.returnLossCheck.setText(_translate("MainWindow", "需测回损"))
        self.saveCurrent.setText(_translate("MainWindow", "临时保存"))
        self.label_3.setText(_translate("MainWindow", "切换间隔："))
        self.switchStep.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "秒"))
        self.label_5.setText(_translate("MainWindow", "测试间隔："))
        self.testStep.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "分"))
        self.label_6.setText(_translate("MainWindow", "测试次数："))
        self.testTime.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "次"))

